# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.refund_reason import RefundReason

class TestRefundReason(unittest.TestCase):
    """RefundReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefundReason(self):
        """Test RefundReason"""
        # inst = RefundReason()

if __name__ == '__main__':
    unittest.main()
