# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.device_data import DeviceData

class TestDeviceData(unittest.TestCase):
    """DeviceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceData:
        """Test DeviceData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceData`
        """
        model = DeviceData()
        if include_optional:
            return DeviceData(
                platform_type = 'mobile',
                os = '0',
                browser = '0',
                language = '',
                timezone_name = '',
                user_agent = ''
            )
        else:
            return DeviceData(
        )
        """

    def testDeviceData(self):
        """Test DeviceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
