# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.payment_details import PaymentDetails

class TestPaymentDetails(unittest.TestCase):
    """PaymentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDetails:
        """Test PaymentDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDetails`
        """
        model = PaymentDetails()
        if include_optional:
            return PaymentDetails(
                payment_id = '',
                order_id = '',
                amount = 1,
                currency = 'RUB',
                description = '',
                payment_method = 'sbp',
                status = 'pending',
                payment_url = '',
                failure_code = '',
                failure_message = '',
                refund_summary = opayments_sdk.models.refund_summary.RefundSummary(
                    refunded_amount = 0, 
                    refundable_amount = 0, 
                    refund_count = 0, ),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                refunds = [
                    {refundId=1d157da7-e7bb-48d8-9b02-5efc00c8c6d0, paymentId=c9ee7c85-4cc0-494f-a0de-0af7257a66a6, amount=50000, currency=RUB, status=accepted, reason=Возврат товара, acceptedAt=2026-09-03T12:06:00Z, createdAt=2026-09-03T12:05:00Z, updatedAt=2026-09-03T12:05:00Z}
                    ]
            )
        else:
            return PaymentDetails(
                payment_id = '',
                order_id = '',
                amount = 1,
                currency = 'RUB',
                payment_method = 'sbp',
                status = 'pending',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPaymentDetails(self):
        """Test PaymentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
