# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.refund_summary import RefundSummary

class TestRefundSummary(unittest.TestCase):
    """RefundSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundSummary:
        """Test RefundSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundSummary`
        """
        model = RefundSummary()
        if include_optional:
            return RefundSummary(
                refunded_amount = 0,
                refundable_amount = 0,
                refund_count = 0
            )
        else:
            return RefundSummary(
                refunded_amount = 0,
                refundable_amount = 0,
                refund_count = 0,
        )
        """

    def testRefundSummary(self):
        """Test RefundSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
