# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.tpay_payment_metadata import TpayPaymentMetadata

class TestTpayPaymentMetadata(unittest.TestCase):
    """TpayPaymentMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TpayPaymentMetadata:
        """Test TpayPaymentMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TpayPaymentMetadata`
        """
        model = TpayPaymentMetadata()
        if include_optional:
            return TpayPaymentMetadata(
                ip = '',
                device_data = None
            )
        else:
            return TpayPaymentMetadata(
                ip = '',
                device_data = None,
        )
        """

    def testTpayPaymentMetadata(self):
        """Test TpayPaymentMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
