# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.api.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentApi()

    def tearDown(self) -> None:
        pass

    def test_create_sbp_payment(self) -> None:
        """Test case for create_sbp_payment

        Создать платёж по СБП
        """
        pass

    def test_create_tpay_payment(self) -> None:
        """Test case for create_tpay_payment

        Создать платёж через T-Pay
        """
        pass


if __name__ == '__main__':
    unittest.main()
