# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.payment_list import PaymentList

class TestPaymentList(unittest.TestCase):
    """PaymentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentList:
        """Test PaymentList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentList`
        """
        model = PaymentList()
        if include_optional:
            return PaymentList(
                items = [
                    {paymentId=c9ee7c85-4cc0-494f-a0de-0af7257a66a6, orderId=order-20260903-001, amount=150000, currency=RUB, description=Подписка за сентябрь, paymentMethod=sbp, status=pending, paymentUrl=https://pay.opayments.io/sbp/c9ee7c85-4cc0-494f-a0de-0af7257a66a6, expiresAt=2026-09-03T12:30:00.000+00:00, createdAt=2026-09-03T12:00:00.000+00:00, updatedAt=2026-09-03T12:00:00.000+00:00}
                    ],
                next_cursor = '',
                has_more = True
            )
        else:
            return PaymentList(
                items = [
                    {paymentId=c9ee7c85-4cc0-494f-a0de-0af7257a66a6, orderId=order-20260903-001, amount=150000, currency=RUB, description=Подписка за сентябрь, paymentMethod=sbp, status=pending, paymentUrl=https://pay.opayments.io/sbp/c9ee7c85-4cc0-494f-a0de-0af7257a66a6, expiresAt=2026-09-03T12:30:00.000+00:00, createdAt=2026-09-03T12:00:00.000+00:00, updatedAt=2026-09-03T12:00:00.000+00:00}
                    ],
                next_cursor = '',
                has_more = True,
        )
        """

    def testPaymentList(self):
        """Test PaymentList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
