# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.create_tpay_payment_request import CreateTpayPaymentRequest

class TestCreateTpayPaymentRequest(unittest.TestCase):
    """CreateTpayPaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTpayPaymentRequest:
        """Test CreateTpayPaymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTpayPaymentRequest`
        """
        model = CreateTpayPaymentRequest()
        if include_optional:
            return CreateTpayPaymentRequest(
                order_id = '0',
                amount = 1,
                description = '',
                metadata = None,
                callback_url = 'https:/',
                success_url = 'https:/',
                failed_url = 'https:/'
            )
        else:
            return CreateTpayPaymentRequest(
                order_id = '0',
                amount = 1,
                metadata = None,
                callback_url = 'https:/',
                success_url = 'https:/',
                failed_url = 'https:/',
        )
        """

    def testCreateTpayPaymentRequest(self):
        """Test CreateTpayPaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
