# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.payment_metadata import PaymentMetadata

class TestPaymentMetadata(unittest.TestCase):
    """PaymentMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMetadata:
        """Test PaymentMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMetadata`
        """
        model = PaymentMetadata()
        if include_optional:
            return PaymentMetadata(
                ip = '',
                device_data = {platformType=desktop, os=macOS, browser=Chrome, language=ru-RU, timezoneName=Europe/Moscow, userAgent=Mozilla/5.0}
            )
        else:
            return PaymentMetadata(
                ip = '',
        )
        """

    def testPaymentMetadata(self):
        """Test PaymentMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
