# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opayments_sdk.models.refund_webhook_notification import RefundWebhookNotification

class TestRefundWebhookNotification(unittest.TestCase):
    """RefundWebhookNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundWebhookNotification:
        """Test RefundWebhookNotification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundWebhookNotification`
        """
        model = RefundWebhookNotification()
        if include_optional:
            return RefundWebhookNotification(
                notification_id = '',
                notification_type = 'refund',
                notification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payment_id = '',
                refund = None
            )
        else:
            return RefundWebhookNotification(
                notification_id = '',
                notification_type = 'refund',
                notification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payment_id = '',
                refund = None,
        )
        """

    def testRefundWebhookNotification(self):
        """Test RefundWebhookNotification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
