# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from opayments_sdk.models.payment_metadata import PaymentMetadata
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateSbpPaymentRequest(BaseModel):
    """
    CreateSbpPaymentRequest
    """ # noqa: E501
    order_id: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(description="Идентификатор заказа в системе мерчанта.", alias="orderId")
    amount: Annotated[int, Field(strict=True, ge=1)] = Field(description="Сумма в копейках.")
    description: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    metadata: PaymentMetadata
    callback_url: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="HTTPS-адрес для уведомлений о платеже.", alias="callbackUrl")
    success_url: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="HTTPS-адрес для успешной оплаты.", alias="successUrl")
    failed_url: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="HTTPS-адрес для отменённой оплаты.", alias="failedUrl")
    __properties: ClassVar[List[str]] = ["orderId", "amount", "description", "metadata", "callbackUrl", "successUrl", "failedUrl"]

    @field_validator('callback_url', mode="before")
    def callback_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^https:\/\/", value):
            raise ValueError(r"must validate the regular expression /^https:\/\//")
        return value

    @field_validator('success_url', mode="before")
    def success_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^https:\/\/", value):
            raise ValueError(r"must validate the regular expression /^https:\/\//")
        return value

    @field_validator('failed_url', mode="before")
    def failed_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^https:\/\/", value):
            raise ValueError(r"must validate the regular expression /^https:\/\//")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSbpPaymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSbpPaymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderId": obj.get("orderId"),
            "amount": obj.get("amount"),
            "description": obj.get("description"),
            "metadata": PaymentMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "callbackUrl": obj.get("callbackUrl"),
            "successUrl": obj.get("successUrl"),
            "failedUrl": obj.get("failedUrl")
        })
        return _obj


