# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from opayments_sdk.models.refund import Refund
from opayments_sdk.models.refund_summary import RefundSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaymentDetails(BaseModel):
    """
    PaymentDetails
    """ # noqa: E501
    payment_id: UUID = Field(alias="paymentId")
    order_id: StrictStr = Field(alias="orderId")
    amount: Annotated[int, Field(strict=True, ge=1)] = Field(description="Сумма в копейках.")
    currency: StrictStr
    description: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    payment_method: StrictStr = Field(alias="paymentMethod")
    status: StrictStr
    payment_url: Optional[StrictStr] = Field(default=None, description="Адрес оплаты для платежа в статусе pending.", alias="paymentUrl")
    failure_code: Optional[StrictStr] = Field(default=None, alias="failureCode")
    failure_message: Optional[StrictStr] = Field(default=None, description="Нормализованное сообщение, безопасное для показа мерчанту; никогда не содержит сырой ответ провайдера, credentials или данные карты.", alias="failureMessage")
    refund_summary: Optional[RefundSummary] = Field(default=None, alias="refundSummary")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    refunds: Optional[List[Refund]] = Field(default=None, description="Устарело, так как список неограничен. Используйте GET /payments/{paymentId}/refunds.")
    __properties: ClassVar[List[str]] = ["paymentId", "orderId", "amount", "currency", "description", "paymentMethod", "status", "paymentUrl", "failureCode", "failureMessage", "refundSummary", "completedAt", "createdAt", "updatedAt", "refunds"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['RUB']):
            raise ValueError("must be one of enum values ('RUB')")
        return value

    @field_validator('payment_method')
    def payment_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['sbp', 'tpay']):
            raise ValueError("must be one of enum values ('sbp', 'tpay')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'succeeded', 'cancelled', 'chargebacked', 'refunded']):
            raise ValueError("must be one of enum values ('pending', 'succeeded', 'cancelled', 'chargebacked', 'refunded')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of refund_summary
        if self.refund_summary:
            _dict['refundSummary'] = self.refund_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in refunds (list)
        _items = []
        if self.refunds:
            for _item_refunds in self.refunds:
                _items.append(_item_refunds.to_dict() if _item_refunds is not None else None)
            _dict['refunds'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentId": obj.get("paymentId"),
            "orderId": obj.get("orderId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "paymentMethod": obj.get("paymentMethod"),
            "status": obj.get("status"),
            "paymentUrl": obj.get("paymentUrl"),
            "failureCode": obj.get("failureCode"),
            "failureMessage": obj.get("failureMessage"),
            "refundSummary": RefundSummary.from_dict(obj["refundSummary"]) if obj.get("refundSummary") is not None else None,
            "completedAt": obj.get("completedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "refunds": [Refund.from_dict(_item) for _item in obj["refunds"]] if obj.get("refunds") is not None else None
        })
        return _obj


