# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from opayments_sdk.models.refund_reason import RefundReason
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PendingRefund(BaseModel):
    """
    PendingRefund
    """ # noqa: E501
    refund_id: UUID = Field(alias="refundId")
    payment_id: UUID = Field(alias="paymentId")
    amount: Annotated[int, Field(strict=True, ge=1)] = Field(description="Сумма в копейках.")
    currency: StrictStr
    status: StrictStr
    reason_code: Optional[RefundReason] = Field(default=None, alias="reasonCode")
    reason_comment: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="reasonComment")
    reason: Optional[StrictStr] = None
    failure_code: Optional[StrictStr] = Field(default=None, alias="failureCode")
    failure_message: Optional[StrictStr] = Field(default=None, alias="failureMessage")
    accepted_at: Optional[datetime] = Field(default=None, alias="acceptedAt")
    declined_at: Optional[datetime] = Field(default=None, alias="declinedAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["refundId", "paymentId", "amount", "currency", "status", "reasonCode", "reasonComment", "reason", "failureCode", "failureMessage", "acceptedAt", "declinedAt", "createdAt", "updatedAt"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['RUB']):
            raise ValueError("must be one of enum values ('RUB')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending']):
            raise ValueError("must be one of enum values ('pending')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PendingRefund from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PendingRefund from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "refundId": obj.get("refundId"),
            "paymentId": obj.get("paymentId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "reasonCode": obj.get("reasonCode"),
            "reasonComment": obj.get("reasonComment"),
            "reason": obj.get("reason"),
            "failureCode": obj.get("failureCode"),
            "failureMessage": obj.get("failureMessage"),
            "acceptedAt": obj.get("acceptedAt"),
            "declinedAt": obj.get("declinedAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


