# coding: utf-8

"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RefundReason(str, Enum):
    """
    RefundReason
    """

    """
    allowed enum values
    """
    REQUESTED_BY_CUSTOMER = 'requested_by_customer'
    DUPLICATE = 'duplicate'
    SUSPECTED_FRAUD = 'suspected_fraud'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RefundReason from a JSON string"""
        return cls(json.loads(json_str))


