"""
    OPayments API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from uuid import UUID
from opayments_sdk.models.payment_details import PaymentDetails
from opayments_sdk.models.payment_list import PaymentList

from opayments_sdk.api_client import ApiClient, RequestSerialized
from opayments_sdk.api_response import ApiResponse
from opayments_sdk.rest import RESTResponseType


class PaymentsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_payment(
        self,
        payment_id: UUID,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentDetails:
        """Получить платёж


        :param payment_id: (required)
        :type payment_id: UUID
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_payment_serialize(
            payment_id=payment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentDetails",
            '400': "Error",
            '401': "Error",
            '404': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_payment_with_http_info(
        self,
        payment_id: UUID,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentDetails]:
        """Получить платёж


        :param payment_id: (required)
        :type payment_id: UUID
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_payment_serialize(
            payment_id=payment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentDetails",
            '400': "Error",
            '401': "Error",
            '404': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_payment_without_preload_content(
        self,
        payment_id: UUID,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Получить платёж


        :param payment_id: (required)
        :type payment_id: UUID
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_payment_serialize(
            payment_id=payment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentDetails",
            '400': "Error",
            '401': "Error",
            '404': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_payment_serialize(
        self,
        payment_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if payment_id is not None:
            _path_params['paymentId'] = payment_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'RequestSignature', 
            'ProjectIdentity'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/payments/{paymentId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_payments(
        self,
        order_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Идентификатор заказа в системе мерчанта.")] = None,
        status: Optional[List[StrictStr]] = None,
        payment_method: Optional[StrictStr] = None,
        amount_from: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не больше amountTo, если он передан.")] = None,
        amount_to: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не меньше amountFrom, если он передан.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Не позже createdTo, если он передан.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Не раньше createdFrom, если он передан.")] = None,
        completed_from: Annotated[Optional[datetime], Field(description="Не позже completedTo, если он передан.")] = None,
        completed_to: Annotated[Optional[datetime], Field(description="Не раньше completedFrom, если он передан.")] = None,
        failure_code: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Нормализованный код причины платежа.")] = None,
        search: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Поиск по paymentId, orderId и описанию платежа.")] = None,
        sort: Optional[StrictStr] = None,
        sort_direction: Optional[StrictStr] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество записей в ответе.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaymentList:
        """Найти платежи

        Возвращает список платежей проекта.

        :param order_id: Идентификатор заказа в системе мерчанта.
        :type order_id: str
        :param status:
        :type status: List[str]
        :param payment_method:
        :type payment_method: str
        :param amount_from: Не больше amountTo, если он передан.
        :type amount_from: int
        :param amount_to: Не меньше amountFrom, если он передан.
        :type amount_to: int
        :param created_from: Не позже createdTo, если он передан.
        :type created_from: datetime
        :param created_to: Не раньше createdFrom, если он передан.
        :type created_to: datetime
        :param completed_from: Не позже completedTo, если он передан.
        :type completed_from: datetime
        :param completed_to: Не раньше completedFrom, если он передан.
        :type completed_to: datetime
        :param failure_code: Нормализованный код причины платежа.
        :type failure_code: str
        :param search: Поиск по paymentId, orderId и описанию платежа.
        :type search: str
        :param sort:
        :type sort: str
        :param sort_direction:
        :type sort_direction: str
        :param cursor: Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.
        :type cursor: str
        :param limit: Количество записей в ответе.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_payments_serialize(
            order_id=order_id,
            status=status,
            payment_method=payment_method,
            amount_from=amount_from,
            amount_to=amount_to,
            created_from=created_from,
            created_to=created_to,
            completed_from=completed_from,
            completed_to=completed_to,
            failure_code=failure_code,
            search=search,
            sort=sort,
            sort_direction=sort_direction,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_payments_with_http_info(
        self,
        order_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Идентификатор заказа в системе мерчанта.")] = None,
        status: Optional[List[StrictStr]] = None,
        payment_method: Optional[StrictStr] = None,
        amount_from: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не больше amountTo, если он передан.")] = None,
        amount_to: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не меньше amountFrom, если он передан.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Не позже createdTo, если он передан.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Не раньше createdFrom, если он передан.")] = None,
        completed_from: Annotated[Optional[datetime], Field(description="Не позже completedTo, если он передан.")] = None,
        completed_to: Annotated[Optional[datetime], Field(description="Не раньше completedFrom, если он передан.")] = None,
        failure_code: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Нормализованный код причины платежа.")] = None,
        search: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Поиск по paymentId, orderId и описанию платежа.")] = None,
        sort: Optional[StrictStr] = None,
        sort_direction: Optional[StrictStr] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество записей в ответе.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaymentList]:
        """Найти платежи

        Возвращает список платежей проекта.

        :param order_id: Идентификатор заказа в системе мерчанта.
        :type order_id: str
        :param status:
        :type status: List[str]
        :param payment_method:
        :type payment_method: str
        :param amount_from: Не больше amountTo, если он передан.
        :type amount_from: int
        :param amount_to: Не меньше amountFrom, если он передан.
        :type amount_to: int
        :param created_from: Не позже createdTo, если он передан.
        :type created_from: datetime
        :param created_to: Не раньше createdFrom, если он передан.
        :type created_to: datetime
        :param completed_from: Не позже completedTo, если он передан.
        :type completed_from: datetime
        :param completed_to: Не раньше completedFrom, если он передан.
        :type completed_to: datetime
        :param failure_code: Нормализованный код причины платежа.
        :type failure_code: str
        :param search: Поиск по paymentId, orderId и описанию платежа.
        :type search: str
        :param sort:
        :type sort: str
        :param sort_direction:
        :type sort_direction: str
        :param cursor: Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.
        :type cursor: str
        :param limit: Количество записей в ответе.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_payments_serialize(
            order_id=order_id,
            status=status,
            payment_method=payment_method,
            amount_from=amount_from,
            amount_to=amount_to,
            created_from=created_from,
            created_to=created_to,
            completed_from=completed_from,
            completed_to=completed_to,
            failure_code=failure_code,
            search=search,
            sort=sort,
            sort_direction=sort_direction,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_payments_without_preload_content(
        self,
        order_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Идентификатор заказа в системе мерчанта.")] = None,
        status: Optional[List[StrictStr]] = None,
        payment_method: Optional[StrictStr] = None,
        amount_from: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не больше amountTo, если он передан.")] = None,
        amount_to: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Не меньше amountFrom, если он передан.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Не позже createdTo, если он передан.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Не раньше createdFrom, если он передан.")] = None,
        completed_from: Annotated[Optional[datetime], Field(description="Не позже completedTo, если он передан.")] = None,
        completed_to: Annotated[Optional[datetime], Field(description="Не раньше completedFrom, если он передан.")] = None,
        failure_code: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Нормализованный код причины платежа.")] = None,
        search: Annotated[Optional[Annotated[str, Field(strict=True, max_length=128)]], Field(description="Поиск по paymentId, orderId и описанию платежа.")] = None,
        sort: Optional[StrictStr] = None,
        sort_direction: Optional[StrictStr] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество записей в ответе.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Найти платежи

        Возвращает список платежей проекта.

        :param order_id: Идентификатор заказа в системе мерчанта.
        :type order_id: str
        :param status:
        :type status: List[str]
        :param payment_method:
        :type payment_method: str
        :param amount_from: Не больше amountTo, если он передан.
        :type amount_from: int
        :param amount_to: Не меньше amountFrom, если он передан.
        :type amount_to: int
        :param created_from: Не позже createdTo, если он передан.
        :type created_from: datetime
        :param created_to: Не раньше createdFrom, если он передан.
        :type created_to: datetime
        :param completed_from: Не позже completedTo, если он передан.
        :type completed_from: datetime
        :param completed_to: Не раньше completedFrom, если он передан.
        :type completed_to: datetime
        :param failure_code: Нормализованный код причины платежа.
        :type failure_code: str
        :param search: Поиск по paymentId, orderId и описанию платежа.
        :type search: str
        :param sort:
        :type sort: str
        :param sort_direction:
        :type sort_direction: str
        :param cursor: Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID.
        :type cursor: str
        :param limit: Количество записей в ответе.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_payments_serialize(
            order_id=order_id,
            status=status,
            payment_method=payment_method,
            amount_from=amount_from,
            amount_to=amount_to,
            created_from=created_from,
            created_to=created_to,
            completed_from=completed_from,
            completed_to=completed_to,
            failure_code=failure_code,
            search=search,
            sort=sort,
            sort_direction=sort_direction,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaymentList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '429': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_payments_serialize(
        self,
        order_id,
        status,
        payment_method,
        amount_from,
        amount_to,
        created_from,
        created_to,
        completed_from,
        completed_to,
        failure_code,
        search,
        sort,
        sort_direction,
        cursor,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'status': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if order_id is not None:
            
            _query_params.append(('orderId', order_id))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if payment_method is not None:
            
            _query_params.append(('paymentMethod', payment_method))
            
        if amount_from is not None:
            
            _query_params.append(('amountFrom', amount_from))
            
        if amount_to is not None:
            
            _query_params.append(('amountTo', amount_to))
            
        if created_from is not None:
            if isinstance(created_from, datetime):
                _query_params.append(
                    (
                        'createdFrom',
                        created_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('createdFrom', created_from))
            
        if created_to is not None:
            if isinstance(created_to, datetime):
                _query_params.append(
                    (
                        'createdTo',
                        created_to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('createdTo', created_to))
            
        if completed_from is not None:
            if isinstance(completed_from, datetime):
                _query_params.append(
                    (
                        'completedFrom',
                        completed_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('completedFrom', completed_from))
            
        if completed_to is not None:
            if isinstance(completed_to, datetime):
                _query_params.append(
                    (
                        'completedTo',
                        completed_to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('completedTo', completed_to))
            
        if failure_code is not None:
            
            _query_params.append(('failureCode', failure_code))
            
        if search is not None:
            
            _query_params.append(('search', search))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if sort_direction is not None:
            
            _query_params.append(('sortDirection', sort_direction))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'RequestSignature', 
            'ProjectIdentity'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/payments',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


